[workspace]
resolver = "3"

members = [
    "vn-runtime",
    "host",
    "tools/asset-packer",
    "tools/xtask",
]

default-members = ["host"]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true